### ISSUE TITLE
Error when using this redirect module

### ISSUE THREAD

**Issue by benwaine** [cfn-modules/alb-redirect-to-https#3]
Hello, 

Can I clarify that the intent of this module is to receive traffic on the port specified by `AlbListenerModule` (eg - 80) and to perform a redirect to the port specified by `RedirectPort`? 

When I navigate to http://mydomain.com no redirect occurs, a 400 http status is returned and what looks like a load balancer served error appears: `400 Bad Request
The plain HTTP request was sent to HTTPS port`. 

Here is my config: 

```yml
  Alb:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        VpcModule: !GetAtt 'Vpc.Outputs.StackName'
        AlertingModule: !GetAtt 'Alerting.Outputs.StackName' # optional
        Scheme: 'internet-facing'
        IdleTimeoutInSeconds: '60' # optional
      TemplateURL: './node_modules/@cfn-modules/alb/module.yml'

  AlbListener:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        AlbModule: !GetAtt 'Alb.Outputs.StackName' # required
        Port: '443'
        CertificateArn: !Ref ALBCertArn  # optional
      TemplateURL: './node_modules/@cfn-modules/alb-listener/module.yml'

  AlbListenerPort80:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        AlbModule: !GetAtt 'Alb.Outputs.StackName' # required
        Port: '80'
        CertificateArn: !Ref ALBCertArn  # optional
      TemplateURL: './node_modules/@cfn-modules/alb-listener/module.yml'

  ALBHttpsRedirectTarget:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        AlbListenerModule: !GetAtt 'AlbListenerPort80.Outputs.StackName' # required
        RedirectPort: '443'
        Priority: '1' # optional
        HostPattern: '' # optional
        PathPattern: '/*' # optional
      TemplateURL: './node_modules/@cfn-modules/alb-redirect-to-https/module.yml'

  Target:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        AlbModule: !GetAtt 'Alb.Outputs.StackName' # required
        AlbListenerModule: !GetAtt 'AlbListener.Outputs.StackName' # required
        VpcModule: !GetAtt 'Vpc.Outputs.StackName' # required
        AlertingModule: !GetAtt 'Alerting.Outputs.StackName'
        Priority: '1' # optional
        HostPattern: !Ref ApiHostTarget # optional
        HealthCheckPath: '/actuator/health'
        DeregistrationDelayInSeconds: '60' # optional
      TemplateURL: './node_modules/@cfn-modules/ecs-alb-target/module.yml'
```

Can you see anything wrong in the way I'm using the module? 

Thanks!

**Comment by michaelwittig** [comment]
Hi @benwaine 
Yes, your assumption is correct and your config also looks good.
Can you check your ALB config in the UI and see if the redirect is properly added?

**Comment by benwaine** [comment]
Sorry, fixing this moved down my priority list a little. 

I figured out the issue: 

```
  AlbListenerPort80:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        AlbModule: !GetAtt 'Alb.Outputs.StackName' # required
        Port: '80'
        CertificateArn: !Ref ALBCertArn  # optional <<<<<<<< !! Should not be set on a listener for none https traffic.
      TemplateURL: './node_modules/@cfn-modules/alb-listener/module.yml'
```

As you can see, a copy and paste error on the listener. 

Thanks, 

Ben
